# Generated by Django 3.0.7 on 2020-07-01 10:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eventing', '0005_auto_20200701_1049'),
        ('accounts', '0002_profile_organ_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(default=datetime.datetime(2020, 7, 1, 10, 35, 28, 305136, tzinfo=utc), verbose_name='زمان ثبت نام')),
                ('Submitter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Profile', verbose_name='ثبت نام کننده')),
                ('submitted_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eventing.Event', verbose_name='رویداد')),
            ],
            options={
                'verbose_name': 'ثبت نام',
                'verbose_name_plural': 'ثبت نام',
            },
        ),
    ]
