# Generated by Django 3.0.7 on 2020-07-01 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='submit_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت نام'),
        ),
    ]
