# Generated by Django 3.0.7 on 2020-07-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200702_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='organ_name',
            field=models.CharField(default='no name', max_length=50, verbose_name='سازمان یا نام رسمی'),
            preserve_default=False,
        ),
    ]
