# Generated by Django 3.0.7 on 2020-07-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200702_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'حقیقی'), (2, 'حقوقی')], null=True, verbose_name='جنسیت'),
        ),
    ]
