# Generated by Django 3.0.7 on 2020-07-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200705_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='cancel',
            field=models.BooleanField(default=False, verbose_name='وضعیت ثبت نام'),
        ),
    ]
