# Generated by Django 3.0.7 on 2020-06-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='trailer',
            field=models.FileField(default='mehdi', upload_to='', verbose_name='پیش نمایش'),
            preserve_default=False,
        ),
    ]
