# Generated by Django 3.0.7 on 2020-06-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventing', '0003_event_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(upload_to='event_posters/', verbose_name='پوستر'),
        ),
        migrations.AlterField(
            model_name='event',
            name='trailer',
            field=models.FileField(upload_to='event_trailers', verbose_name='پیش نمایش'),
        ),
    ]
