# Generated by Django 3.0.7 on 2020-07-01 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_organ_name'),
        ('eventing', '0004_auto_20200628_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Profile', verbose_name='برگزار کننده'),
        ),
        migrations.AlterField(
            model_name='event',
            name='trailer',
            field=models.FileField(null=True, upload_to='event_trailers', verbose_name='پیش نمایش'),
        ),
    ]
