# Generated by Django 3.0.7 on 2020-07-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventing', '0005_auto_20200701_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='عنوان'),
        ),
    ]
