# Generated by Django 3.0.7 on 2020-07-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventing', '0006_auto_20200701_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ticket',
        ),
        migrations.AddField(
            model_name='event',
            name='situation',
            field=models.IntegerField(choices=[(1, 'رویداد آغاز نشده'), (3, 'رویداد آغاز شده'), (2, 'رویداد پایان یافت'), (4, 'رویداد لغو شده')], default=1, verbose_name='وضعیت رویداد'),
        ),
    ]
