# Generated by Django 3.0.7 on 2020-07-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventing', '0008_auto_20200702_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='subject',
            field=models.CharField(choices=[('computer science', 'علوم رایانه'), ('data science', 'علم داده'), ('big data', 'کلان داده'), ('artificial intelligence', 'هوش مصنوعی'), ('security', 'امنیت'), ('software engineering', 'مهندسی نرافزار'), ('develop', 'توسعه\u200cی نرم افزار'), ('cryptography', 'رمزنگاری'), ('crypto currency', 'رمز ارز'), ('IOT', 'اینترنت اشیا'), ('startup', 'استارتاپ')], max_length=30, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=70, unique=True, verbose_name='عنوان'),
        ),
    ]
