# Generated by Django 3.0.7 on 2020-07-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventing', '0010_event_made_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancel',
            field=models.BooleanField(default=False, verbose_name='وضعیت لغو'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='برچسب ها'),
        ),
    ]
