# Generated by Django 3.0.7 on 2020-07-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventing', '0011_auto_20200706_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end',
            field=models.BooleanField(default=False, verbose_name='پایان'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cancel',
            field=models.BooleanField(default=False, verbose_name='لغو'),
        ),
    ]
