# Generated by Django 3.0.7 on 2020-07-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventing', '0012_auto_20200706_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='verify',
            field=models.BooleanField(blank=True, default=False, verbose_name='تایید'),
        ),
        migrations.AlterField(
            model_name='event',
            name='cancel',
            field=models.BooleanField(blank=True, default=False, verbose_name='لغو'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.BooleanField(blank=True, default=False, verbose_name='پایان'),
        ),
        migrations.AlterField(
            model_name='event',
            name='situation',
            field=models.IntegerField(blank=True, choices=[(1, 'رویداد آغاز نشده'), (3, 'رویداد آغاز شده'), (2, 'رویداد پایان یافت'), (4, 'رویداد لغو شده')], default=1, verbose_name='وضعیت رویداد'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='برچسب ها'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='عنوان'),
        ),
    ]
