# Generated by Django 3.0.7 on 2020-08-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventing', '0013_auto_20200728_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='situation',
            field=models.IntegerField(blank=True, choices=[(1, 'رویداد آغاز نشده'), (3, 'رویداد آغاز شده'), (2, 'رویداد پایان یافت'), (4, 'رویداد لغو شده'), (5, 'در انتظار تایید')], default=1, verbose_name='وضعیت رویداد'),
        ),
    ]
